=== lmontejo91/Ejercicio-12.9.-XML_Schema_XSLT/schemaBiblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="biblioteca">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="libro" minOccurs="5" maxOccurs="unbounded" type="estructura_libro"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:complexType name="estructura_libro">
    <xs:sequence>
        <xs:element name="isbn" type="tipo_isbn"/>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="autor" type="tipo_autor"/>
        <xs:element name="anio_publicacion" type="xs:date"/>
        <xs:element name="precio" type="tipo_precio"/>
        <xs:element name="estanteria" type="tipo_estanteria"/>
    </xs:sequence>
    <xs:attribute name="lang" type="xs:string" use="required"/>
    <xs:attribute name="estado" use="required">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="prestado"/>
                <xs:enumeration value="libre"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="cover" type="xs:string"/>  
</xs:complexType>

<xs:simpleType name="tipo_isbn">
    <xs:restriction base="xs:integer">
        <xs:pattern value="[0-9]{10}"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="tipo_autor">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-Za-zÀ-ÿ\.]+(\s[A-Za-zÀ-ÿ\.]+)*"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="tipo_precio">
    <xs:restriction base="xs:decimal">
        <xs:maxInclusive value="100"/>
        <xs:fractionDigits value="2"/> <!-- Limita el número de decimales que se pueden poner a dos. -->
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="tipo_estanteria">
    <xs:restriction base="xs:string">
        <xs:pattern value="HIS|ROM|FIC|FAN|CLA|MIS[0-9]{4}"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== lmontejo91/Ejercicio-12.9.-XML_Schema_XSLT/Ejercicio12.9_Biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schemaBiblioteca.xsd">
    <libro lang="es" estado="libre" cover="hardcover">
        <isbn>8478886540</isbn>
        <titulo>Harry Potter y la piedra filosofal</titulo>
        <autor>J K. Rowling</autor>
        <anio_publicacion>1997-06-26</anio_publicacion>
        <precio>29.99</precio>
        <estanteria>FAN1234**</estanteria>
    </libro>
    
    <libro estado="libre" cover="paperback">
        <isbn>1501110365</isbn>
        <titulo>It Ends with Us</titulo>
        <autor>Colleen Hoover</autor>
        <anio_publicacion>2016-08-02</anio_publicacion>
        <precio>19.99</precio>
        <estanteria>ROM1234**</estanteria>
    </libro>
    
    <libro lang="en" estado="prestado" cover="hardcover">
        <isbn>0765326353</isbn>
        <titulo>The Way of Kings</titulo>
        <autor>Brandon Sanderson</autor>
        <anio_publicacion>2010-08-31</anio_publicacion>
        <precio>39.95</precio>
        <estanteria>FAN4567**</estanteria>
    </libro>

    <libro lang="es" estado="libre" cover="paperback">
        <isbn>8423648990</isbn>
        <titulo>Marina</titulo>
        <autor>Carlos Ruiz Zafón</autor>
        <anio_publicacion>1999-03-25</anio_publicacion>
        <precio>22.99</precio>
        <estanteria>FIC1234**</estanteria>
    </libro>

    <libro lang="es" estado="libre" cover="paperback">
        <isbn>8497594258</isbn>
        <titulo>Un mundo feliz</titulo>
        <autor>Aldous Huxley</autor>
        <anio_publicacion>1932-01-07</anio_publicacion>
        <precio>29.99</precio>
        <estanteria>FAN1234**</estanteria>
    </libro>

    <libro lang="es" estado="libre" cover="paperback">
        <isbn>9876780042</isbn>
        <titulo>Cumbres Borrascosas</titulo>
        <autor>Emily Brontë</autor>
        <anio_publicacion>1847-04-26</anio_publicacion>
        <precio>21.39</precio>
        <estanteria>CLA1234**</estanteria>
    </libro>

    <libro lang="es" estado="libre" cover="paperback">
        <isbn>0553213105</isbn>
        <titulo>Orgullo y prejuicio</titulo>
        <autor>Jane Austen</autor>
        <anio_publicacion>1813-03-13</anio_publicacion>
        <precio>20.39</precio>
        <estanteria>CLA1234**</estanteria>
    </libro>

</biblioteca>
